### ISSUE TITLE
Make netstring installation easier

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/virtualchain#4]
The package is hosted externally at PyPi and it took me a while to figure out that the correct command to install this is:

> pip install --allow-external netstring --allow-unverified netstring netstring==1.0.0

Which results in:

```
Collecting netstring==1.0.0
  netstring is potentially insecure and unverifiable.
  Downloading http://netstring.googlecode.com/files/netstring-1.0.0.zip
Installing collected packages: netstring
  Running setup.py install for netstring
Successfully installed netstring-1.0.0
```

I'm going to try and see what happens with setup.py.

**Comment by muneeb-ali** [comment]
@peacekeeper I think you were having trouble installing netstring and the above command might help.

**Comment by jcnelson** [comment]
The `netstring` package is public-domain, stable, and small enough that I could maintain a fork (the module is exactly one .py file).  We can directly include it in virtualchain if it makes packaging easier.

**Comment by muneeb-ali** [comment]
Rolling it directly into virtualchain might work well.

**Comment by jcnelson** [comment]
Added

**Comment by muneeb-ali** [comment]
Awesome! Closing this issue.
